### ISSUE TITLE
Security vulnerabilities in dependencies

### ISSUE THREAD

**Issue by ain** [verbose/verb#110]
Running `npm audit` reveals `31 vulnerabilities (21 low, 9 high, 1 critical)`

**Comment by ain** [comment]
I've highlighted the subjected dependencies in 5c8b80b.

**Comment by tunnckoCore** [comment]
Is it against the master? Most recent and used is in (STILL! for years ;d) in the dev branch.

**Comment by jonschlinkert** [comment]
Unless someone is running verb's devDependencies on a production server, there is no reason at all for us to ever be concerned with these "vulnerabilities".

**Comment by jonschlinkert** [comment]
Also, unless the vulnerability is directly in verb, you should create issues on the mentioned libraries. Those libraries should submit patches to fix the vulnerabilities. We should not be expected to bump majors to fix a security issue.

**Comment by ain** [comment]
Understood. 

CVE often (if not mostly) also includes memory issues, such as leaks, so even if it is essentially a development-bound dependency, it's still relevant to follow up.

**Comment by jonschlinkert** [comment]
> even if it is essentially a development-bound dependency, it's still relevant to follow up.

Agreed, but we should focus our energy on forcing authors of those libraries to fix the root of the problem, instead of [hacking at the leaves](https://www.goodreads.com/quotes/54372-there-are-a-thousand-hacking-at-the-branches-of-evil) by creating issues on dependant libraries. 

IMHO, it's not okay for the maintainers of those libs to ask implementors to bump a major to fix a security issue. They need to release patches so that everyone gets the fixes automatically. I personally think we should all stand our ground on that.

**Comment by jonschlinkert** [comment]
however, I do appreciate that you care and that you took the time to create issues about it. I should have made that clear as well.
