### ISSUE TITLE
0.9.0: passing options to `toc` (for example `opts.filter`), and expose TOC helper to template

### ISSUE THREAD

**Issue by tunnckoCore** [verbose/verb#95]
Because currently it is not exposed for use with `{%= toc() %}`, you can do only using html comment.
Also passing custom options to toc isn't possible, overwriting also is not possible, even through verb config - for example `verb.toc.footer` does not overwrite the default footer of toc.

```md
<!-- toc('*.md', {filter: fn}) -->
```

**Comment by jonschlinkert** [comment]
closing since there is no `toc` logic verb. If necessary, create this issue on verb-readme-generator, wich uses `verb-toc` middleware. Options are already passed to the middleware, but it doesn't do the things you probably want. You might better off creating a custom toc middleware or helper that does what you want.

**Comment by tunnckoCore** [comment]
> Options are already passed to

And how to pass filter option? Anad what options "works".

**Comment by jonschlinkert** [comment]
> And how to pass filter option? And what options "works"?

I can make sure options are passed to markdown-toc if that's what you mean. but that would be an issue for `verb-toc`
